import type { PipelineEdge, PipelineNode, TableRegistryEntry } from './types.js';

/** Curated ownership + purpose. Unknown tables get inferred at runtime. */
export const TABLE_REGISTRY: Record<string, TableRegistryEntry> = {
  // ── Collections ──
  collection_targets: {
    table: 'collection_targets',
    category: 'collections',
    owner: 'harvest',
    lifecycle: 'active',
    purpose: 'Registry of collection targets enqueued to Cascades workflows.',
    service: 'harvest',
    apis: ['/api/collection/targets', '/api/harvest/targets'],
    canDelete: false,
    canArchive: false,
    canPartition: false,
    referencedBy: ['osint_harvest_runs', 'collections'],
  },
  collection_target_dependencies: {
    table: 'collection_target_dependencies',
    category: 'collections',
    owner: 'harvest',
    lifecycle: 'active',
    purpose: 'Dependency graph between collection targets.',
    service: 'harvest',
    canDelete: false,
    canArchive: false,
    canPartition: false,
    references: ['collection_targets'],
  },
  collection_policies: {
    table: 'collection_policies',
    category: 'collections',
    owner: 'harvest',
    lifecycle: 'active',
    purpose: 'Policy rules governing collection behavior per target type.',
    service: 'harvest',
    apis: ['/api/collection/policies'],
    canDelete: false,
    canArchive: false,
    canPartition: false,
  },
  collections: {
    table: 'collections',
    category: 'collections',
    owner: 'harvest',
    lifecycle: 'active',
    purpose: 'Intelligence collection runs — parent aggregate for artifacts and observations.',
    service: 'harvest',
    apis: ['/api/intelligence/v1/collections/:id'],
    canDelete: false,
    canArchive: true,
    canPartition: true,
    referencedBy: ['source_artifacts', 'osint_harvest_findings', 'observed_entities'],
  },
  osint_harvest_runs: {
    table: 'osint_harvest_runs',
    category: 'collections',
    owner: 'harvest',
    lifecycle: 'active',
    purpose: 'Legacy/cli harvest run ledger; bridged to Cascades workflow runs.',
    service: 'harvest',
    apis: ['/api/harvest/status', '/api/harvest/runs/:id'],
    canDelete: false,
    canArchive: true,
    canPartition: true,
    references: ['collection_targets'],
    referencedBy: ['osint_harvest_findings'],
  },

  // ── Intelligence ──
  osint_harvest_findings: {
    table: 'osint_harvest_findings',
    category: 'intelligence',
    owner: 'harvest',
    lifecycle: 'active',
    purpose: 'Primary observation store — passive OSINT findings from collection.',
    service: 'harvest',
    apis: ['/api/intelligence/v1/observations', '/api/harvest/status'],
    canDelete: false,
    canArchive: true,
    canPartition: true,
    references: ['collections', 'osint_harvest_runs'],
    referencedBy: ['observed_entities', 'provenance'],
  },
  source_artifacts: {
    table: 'source_artifacts',
    category: 'intelligence',
    owner: 'harvest',
    lifecycle: 'active',
    purpose: 'Raw connector payloads normalized to ontology before extraction.',
    service: 'harvest',
    apis: ['/api/intelligence/v1/collections/:id/artifacts'],
    canDelete: false,
    canArchive: true,
    canPartition: true,
    references: ['collections'],
    referencedBy: ['extraction_runs', 'observed_entities'],
  },
  extraction_runs: {
    table: 'extraction_runs',
    category: 'intelligence',
    owner: 'harvest',
    lifecycle: 'active',
    purpose: 'Extraction passes over source artifacts into observed entities.',
    service: 'harvest',
    canDelete: false,
    canArchive: true,
    canPartition: true,
    references: ['source_artifacts'],
    referencedBy: ['observed_entities'],
  },
  observed_entities: {
    table: 'observed_entities',
    category: 'intelligence',
    owner: 'harvest',
    lifecycle: 'active',
    purpose: 'Entities extracted from artifacts — bridge to STIX and graph.',
    service: 'harvest',
    canDelete: false,
    canArchive: true,
    canPartition: true,
    references: ['source_artifacts', 'osint_harvest_findings'],
    referencedBy: ['stix_objects', 'collection_relationships', 'resolved_entities'],
  },
  stix_objects: {
    table: 'stix_objects',
    category: 'intelligence',
    owner: 'harvest',
    lifecycle: 'active',
    purpose: 'STIX 2.1 object store derived from observations.',
    service: 'harvest',
    apis: ['/api/intelligence/v1/collections/:id/export/stix'],
    canDelete: false,
    canArchive: true,
    canPartition: true,
    references: ['observed_entities'],
    referencedBy: ['stix_attribute_history', 'stix_object_sources'],
  },
  stix_attribute_history: {
    table: 'stix_attribute_history',
    category: 'intelligence',
    owner: 'harvest',
    lifecycle: 'active',
    purpose: 'Immutable history of STIX attribute evolution.',
    service: 'harvest',
    canDelete: false,
    canArchive: true,
    canPartition: true,
    references: ['stix_objects'],
  },
  stix_object_sources: {
    table: 'stix_object_sources',
    category: 'intelligence',
    owner: 'harvest',
    lifecycle: 'active',
    purpose: 'Provenance links from STIX objects back to source artifacts.',
    service: 'harvest',
    canDelete: false,
    canArchive: true,
    canPartition: false,
    references: ['stix_objects', 'source_artifacts'],
  },
  provenance: {
    table: 'provenance',
    category: 'intelligence',
    owner: 'harvest',
    lifecycle: 'active',
    purpose: 'Lineage chain for observations and intelligence objects.',
    service: 'harvest',
    apis: ['/api/intelligence/v1/provenance/:id/chain'],
    canDelete: false,
    canArchive: true,
    canPartition: true,
    references: ['osint_harvest_findings'],
  },
  collection_relationships: {
    table: 'collection_relationships',
    category: 'intelligence',
    owner: 'harvest',
    lifecycle: 'active',
    purpose: 'Graph edges between observed entities within collections.',
    service: 'harvest',
    apis: ['/api/intelligence/v1/graph/neighbors'],
    canDelete: false,
    canArchive: true,
    canPartition: false,
    references: ['observed_entities'],
  },
  resolved_entities: {
    table: 'resolved_entities',
    category: 'intelligence',
    owner: 'harvest',
    lifecycle: 'active',
    purpose: 'Identity resolution clusters across observations.',
    service: 'harvest',
    canDelete: false,
    canArchive: true,
    canPartition: false,
    references: ['observed_entities'],
  },
  knowledge_objects: {
    table: 'knowledge_objects',
    category: 'knowledge',
    owner: 'harvest',
    lifecycle: 'active',
    purpose: 'Synthesized knowledge artifacts (profiles, summaries, networks).',
    service: 'harvest',
    apis: ['/api/intelligence/v1/knowledge'],
    canDelete: false,
    canArchive: true,
    canPartition: false,
    references: ['collections'],
  },
  claims: {
    table: 'claims',
    category: 'knowledge',
    owner: 'harvest',
    lifecycle: 'active',
    purpose: 'Analytic claims with evidence linkage and review status.',
    service: 'harvest',
    apis: ['/api/intelligence/v1/claims'],
    canDelete: false,
    canArchive: true,
    canPartition: false,
  },

  // ── Community ──
  community_items: {
    table: 'community_items',
    category: 'community',
    owner: 'harvest',
    lifecycle: 'active',
    purpose: 'Community intelligence feed items (sensor, narrative, authority).',
    service: 'harvest',
    apis: ['/api/feeds/community/items', '/api/feeds/community/facets', '/api/feeds/community/expand', 'judicium:/api/community/items'],
    canDelete: false,
    canArchive: true,
    canPartition: true,
    references: ['feed_items'],
  },
  feed_items: {
    table: 'feed_items',
    category: 'community',
    owner: 'shared',
    lifecycle: 'active',
    purpose: 'RSS/news ingestion store; primary in Judicium PG, mirrored in Harvest.',
    service: 'harvest',
    apis: ['/api/feeds/community', 'judicium:/api/news'],
    canDelete: false,
    canArchive: true,
    canPartition: true,
    referencedBy: ['community_items'],
  },
  feed_health: {
    table: 'feed_health',
    category: 'community',
    owner: 'shared',
    lifecycle: 'active',
    purpose: 'Mutable feed health state — consider projecting from domain_events over time.',
    service: 'harvest',
    apis: ['judicium:/api/feeds/health'],
    canDelete: false,
    canArchive: false,
    canPartition: false,
  },

  // ── Ontology ──
  ontology_entity_types: {
    table: 'ontology_entity_types',
    category: 'ontology',
    owner: 'harvest',
    lifecycle: 'active',
    purpose: 'Entity type definitions for Intelligence Core v1.',
    service: 'harvest',
    apis: ['/api/intelligence/v1/ontology'],
    canDelete: false,
    canArchive: false,
    canPartition: false,
  },
  ontology_observable_types: {
    table: 'ontology_observable_types',
    category: 'ontology',
    owner: 'harvest',
    lifecycle: 'active',
    purpose: 'Observable SCO types mapped to connectors.',
    service: 'harvest',
    apis: ['/api/intelligence/v1/ontology'],
    canDelete: false,
    canArchive: false,
    canPartition: false,
  },
  ontology_relationship_types: {
    table: 'ontology_relationship_types',
    category: 'ontology',
    owner: 'harvest',
    lifecycle: 'active',
    purpose: 'Relationship types for graph engine.',
    service: 'harvest',
    canDelete: false,
    canArchive: false,
    canPartition: false,
  },
  ontology_knowledge_types: {
    table: 'ontology_knowledge_types',
    category: 'ontology',
    owner: 'harvest',
    lifecycle: 'active',
    purpose: 'Knowledge object type taxonomy.',
    service: 'harvest',
    canDelete: false,
    canArchive: false,
    canPartition: false,
  },

  // ── Execution (Cascades + platform) ──
  workflow_runs: {
    table: 'workflow_runs',
    category: 'execution',
    owner: 'cascades',
    lifecycle: 'active',
    purpose: 'Cascades workflow execution records stored in Harvest PG.',
    service: 'cascades',
    apis: ['cascades:/dashboard/workflow', '/api/collection/steps/*'],
    canDelete: false,
    canArchive: true,
    canPartition: true,
    referencedBy: ['task_runs', 'run_events', 'execution_logs'],
  },
  task_runs: {
    table: 'task_runs',
    category: 'execution',
    owner: 'cascades',
    lifecycle: 'active',
    purpose: 'Per-node task execution within Cascades workflows.',
    service: 'cascades',
    canDelete: false,
    canArchive: true,
    canPartition: true,
    references: ['workflow_runs'],
  },
  execution_logs: {
    table: 'execution_logs',
    category: 'execution',
    owner: 'cascades',
    lifecycle: 'active',
    purpose: 'Connector step logs from Cascades DAG engine.',
    service: 'cascades',
    canDelete: false,
    canArchive: true,
    canPartition: true,
    references: ['workflow_runs'],
  },
  run_events: {
    table: 'run_events',
    category: 'execution',
    owner: 'cascades',
    lifecycle: 'active',
    purpose: 'Fine-grained events emitted during workflow runs.',
    service: 'cascades',
    canDelete: false,
    canArchive: true,
    canPartition: true,
    references: ['workflow_runs'],
  },
  workflows: {
    table: 'workflows',
    category: 'execution',
    owner: 'cascades',
    lifecycle: 'active',
    purpose: 'Registered Cascades workflow definitions.',
    service: 'cascades',
    canDelete: false,
    canArchive: false,
    canPartition: false,
  },

  // ── Events ──
  domain_events: {
    table: 'domain_events',
    category: 'system',
    owner: 'harvest',
    lifecycle: 'active',
    purpose: 'Cross-cutting domain event log — foundation for event-sourced projections.',
    service: 'harvest',
    canDelete: false,
    canArchive: true,
    canPartition: true,
  },
  collection_events: {
    table: 'collection_events',
    category: 'system',
    owner: 'harvest',
    lifecycle: 'active',
    purpose: 'Collection-specific event projection.',
    service: 'harvest',
    canDelete: false,
    canArchive: true,
    canPartition: true,
    references: ['domain_events'],
  },
  observation_events: {
    table: 'observation_events',
    category: 'system',
    owner: 'harvest',
    lifecycle: 'active',
    purpose: 'Observation lifecycle events.',
    service: 'harvest',
    canDelete: false,
    canArchive: true,
    canPartition: true,
  },

  // ── Schema bleed (Judicium tables in Harvest DB) ──
  cases: {
    table: 'cases',
    category: 'schema-bleed',
    owner: 'judicium',
    lifecycle: 'schema-bleed',
    purpose: 'Investigation cases — owned by Judicium SQLite/PG, not Harvest operations.',
    service: 'judicium',
    apis: ['judicium:/api/cases'],
    canDelete: false,
    canArchive: false,
    canPartition: false,
  },
  evidence: {
    table: 'evidence',
    category: 'schema-bleed',
    owner: 'judicium',
    lifecycle: 'schema-bleed',
    purpose: 'Evidence shelf — Judicium workbench only.',
    service: 'judicium',
    apis: ['judicium:/api/evidence'],
    canDelete: false,
    canArchive: false,
    canPartition: false,
  },
  discord_messages: {
    table: 'discord_messages',
    category: 'schema-bleed',
    owner: 'judicium',
    lifecycle: 'planned',
    purpose: 'Discord connector cache — planned Judicium feature, empty in Harvest DB.',
    service: 'judicium',
    canDelete: true,
    canArchive: false,
    canPartition: false,
  },
  telegram_posts: {
    table: 'telegram_posts',
    category: 'schema-bleed',
    owner: 'judicium',
    lifecycle: 'planned',
    purpose: 'Telegram connector cache — Judicium only.',
    service: 'judicium',
    canDelete: true,
    canArchive: false,
    canPartition: false,
  },
  social_posts: {
    table: 'social_posts',
    category: 'schema-bleed',
    owner: 'judicium',
    lifecycle: 'planned',
    purpose: 'Social ingestion — Judicium connector layer.',
    service: 'judicium',
    canDelete: true,
    canArchive: false,
    canPartition: false,
  },
  youtube_videos: {
    table: 'youtube_videos',
    category: 'schema-bleed',
    owner: 'judicium',
    lifecycle: 'planned',
    purpose: 'YouTube connector — not wired in production.',
    service: 'judicium',
    canDelete: true,
    canArchive: false,
    canPartition: false,
  },
  redfin_metrics: {
    table: 'redfin_metrics',
    category: 'schema-bleed',
    owner: 'judicium',
    lifecycle: 'inactive',
    purpose: 'Redfin housing import — Judicium analytics, optional.',
    service: 'judicium',
    apis: ['judicium:/api/redfin/*'],
    canDelete: true,
    canArchive: true,
    canPartition: false,
  },
  redfin_import_log: {
    table: 'redfin_import_log',
    category: 'schema-bleed',
    owner: 'judicium',
    lifecycle: 'inactive',
    purpose: 'Redfin ETL log — safe to drop from Harvest DB if empty.',
    service: 'judicium',
    canDelete: true,
    canArchive: true,
    canPartition: false,
    references: ['redfin_metrics'],
  },
  fusion_items: {
    table: 'fusion_items',
    category: 'schema-bleed',
    owner: 'judicium',
    lifecycle: 'schema-bleed',
    purpose: 'H3XA fusion inbox — lives in Judicium SQLite primarily.',
    service: 'judicium',
    apis: ['judicium:/api/fusion/inbox'],
    canDelete: false,
    canArchive: true,
    canPartition: false,
  },
};

export const PIPELINE_NODES: PipelineNode[] = [
  {
    id: 'targets',
    label: 'Collection Targets',
    owner: 'harvest',
    tables: ['collection_targets'],
    description: 'Registry of what to collect; enqueued to Cascades.',
  },
  {
    id: 'cascades',
    label: 'Cascades Workflows',
    owner: 'cascades',
    tables: ['workflows', 'workflow_runs', 'task_runs', 'execution_logs'],
    description: 'Connector DAG execution — OSINT steps, transforms, publishes.',
  },
  {
    id: 'harvest-run',
    label: 'Harvest Run',
    owner: 'harvest',
    tables: ['osint_harvest_runs', 'collections'],
    description: 'Run ledger tying Cascades output to collection aggregates.',
  },
  {
    id: 'findings',
    label: 'Findings',
    owner: 'harvest',
    tables: ['osint_harvest_findings'],
    description: 'Normalized observations from passive/active collection.',
  },
  {
    id: 'artifacts',
    label: 'Source Artifacts',
    owner: 'harvest',
    tables: ['source_artifacts', 'extraction_runs'],
    description: 'Raw connector payloads + extraction passes.',
  },
  {
    id: 'entities',
    label: 'Observed Entities',
    owner: 'harvest',
    tables: ['observed_entities', 'collection_relationships'],
    description: 'Entity graph extracted from artifacts.',
  },
  {
    id: 'stix',
    label: 'STIX Objects',
    owner: 'harvest',
    tables: ['stix_objects', 'stix_object_sources'],
    description: 'STIX 2.1 representation for interchange.',
  },
  {
    id: 'history',
    label: 'STIX History',
    owner: 'harvest',
    tables: ['stix_attribute_history'],
    description: 'Immutable attribute mutation log.',
  },
  {
    id: 'community',
    label: 'Community',
    owner: 'harvest',
    tables: ['community_items', 'feed_items'],
    description: 'Published situational awareness for Judicium map.',
  },
  {
    id: 'judicium',
    label: 'Judicium Workbench',
    owner: 'judicium',
    tables: ['cases', 'evidence'],
    description: 'Investigation dossiers — SQLite primary, consumes Intelligence API.',
  },
];

export const PIPELINE_EDGES: PipelineEdge[] = [
  { from: 'targets', to: 'cascades', label: 'enqueue workflow' },
  { from: 'cascades', to: 'harvest-run', label: 'run complete' },
  { from: 'cascades', to: 'artifacts', label: 'connector output' },
  { from: 'harvest-run', to: 'findings', label: 'persist observations' },
  { from: 'artifacts', to: 'entities', label: 'extract' },
  { from: 'findings', to: 'entities', label: 'resolve' },
  { from: 'entities', to: 'stix', label: 'materialize STIX' },
  { from: 'stix', to: 'history', label: 'record changes' },
  { from: 'findings', to: 'community', label: 'publish layers' },
  { from: 'stix', to: 'judicium', label: 'intelligence API' },
  { from: 'community', to: 'judicium', label: 'proxy feeds' },
];

export function inferRegistry(table: string, databaseId: string): TableRegistryEntry {
  const known = TABLE_REGISTRY[table];
  if (known) {
    if (databaseId === 'harvest' && known.owner !== 'harvest' && known.owner !== 'cascades' && known.owner !== 'shared') {
      return { ...known, lifecycle: 'schema-bleed', category: 'schema-bleed' };
    }
    return known;
  }
  const owner =
    databaseId === 'judicium' ? 'judicium' : databaseId === 'h3xa' ? 'h3xa' : 'harvest';
  return {
    table,
    category: databaseId !== 'harvest' && owner !== 'harvest' ? 'system' : 'system',
    owner,
    lifecycle: 'inactive',
    purpose: 'Undocumented table — add to TABLE_REGISTRY in src/data-catalog/registry.ts.',
    canDelete: false,
    canArchive: false,
    canPartition: false,
  };
}

export function statusLabel(entry: TableRegistryEntry, rows: number, databaseId: string): string {
  if (entry.lifecycle === 'schema-bleed' || (databaseId === 'harvest' && entry.owner === 'judicium')) {
    return rows > 0 ? 'Shared schema — data present, owner is Judicium' : 'Shared schema — not active in Harvest';
  }
  if (entry.lifecycle === 'planned') return rows > 0 ? 'Planned feature — has data' : 'Planned — not wired';
  if (rows === 0) return entry.lifecycle === 'inactive' ? 'Inactive — empty' : 'Empty — awaiting data';
  return 'Active';
}
