import React, { useCallback, useEffect, useState } from 'react';
import {
  Database, RefreshCw, ChevronRight, Activity, GitBranch, Layers, AlertTriangle, Box, BookOpen, Route,
} from 'lucide-react';
import { cn } from '../types';
import type { CatalogCategory, CatalogTableCard, DataCatalogResponse, DataLineageView, TableNarrative } from '../data-catalog/types';

const CATEGORY_LABELS: Record<CatalogCategory, string> = {
  knowledge: 'Knowledge',
  collections: 'Collections',
  intelligence: 'Intelligence',
  community: 'Community',
  ontology: 'Ontology',
  execution: 'Execution',
  system: 'System',
  'schema-bleed': 'Schema Bleed',
};

const HEAT_STYLES: Record<string, string> = {
  healthy: 'border-emerald-500/30 bg-emerald-500/[0.06] text-emerald-400/80',
  'append-only': 'border-sky-500/30 bg-sky-500/[0.06] text-sky-400/80',
  'update-heavy': 'border-amber-500/30 bg-amber-500/[0.06] text-amber-400/80',
  unused: 'border-ink/[0.08] bg-ink/[0.03] text-ink/35',
  'needs-attention': 'border-rose-500/30 bg-rose-500/[0.06] text-rose-400/80',
};

function TableCard({
  card,
  onSelect,
  selected,
}: {
  card: CatalogTableCard;
  onSelect: (c: CatalogTableCard) => void;
  selected: boolean;
}) {
  const live = card.live;
  return (
    <button
      type="button"
      onClick={() => onSelect(card)}
      className={cn(
        'w-full text-left border p-3 transition-colors',
        selected ? 'border-ink/25 bg-ink/[0.06]' : 'border-ink/[0.06] hover:border-ink/[0.12] hover:bg-ink/[0.03]',
        live && HEAT_STYLES[live.heat],
      )}
    >
      <div className="flex items-start justify-between gap-2">
        <div>
          <div className="text-[11px] font-mono font-semibold uppercase tracking-wide">{card.table}</div>
          <div className="text-[10px] text-ink/40 mt-0.5">{card.databaseLabel} · {card.registry.owner}</div>
        </div>
        <ChevronRight size={12} className="text-ink/30 shrink-0 mt-1" />
      </div>
      {live && (
        <div className="mt-2 grid grid-cols-3 gap-2 text-[10px]">
          <div><span className="text-ink/35">Rows</span><div className="font-mono">{live.rows.toLocaleString()}</div></div>
          <div><span className="text-ink/35">Size</span><div className="font-mono">{live.sizePretty}</div></div>
          <div><span className="text-ink/35">Idx%</span><div className="font-mono">{live.idxPct}%</div></div>
        </div>
      )}
      <div className="mt-2 text-[10px] text-ink/45">{card.statusLabel}</div>
    </button>
  );
}

function NarrativeBlock({ narrative }: { narrative: TableNarrative }) {
  return (
    <div className="space-y-3 border border-ink/[0.08] bg-ink/[0.02] p-4">
      <div className="flex items-center gap-2 text-[10px] uppercase tracking-wider text-ink/45">
        <BookOpen size={12} /> Why does this table exist?
      </div>
      <div>
        <div className="text-[10px] uppercase text-ink/35 mb-1">Purpose</div>
        <p className="text-[11px] text-ink/65 leading-relaxed">{narrative.purposeDetail}</p>
      </div>
      <div>
        <div className="text-[10px] uppercase text-ink/35 mb-1">Why it exists</div>
        <p className="text-[11px] text-ink/55 leading-relaxed italic">{narrative.whyItExists}</p>
      </div>
      {narrative.generatedBy?.length ? (
        <div>
          <div className="text-[10px] uppercase text-ink/35 mb-1">Generated by</div>
          <div className="flex flex-wrap gap-1">
            {narrative.generatedBy.map((g) => (
              <span key={g} className="px-2 py-0.5 border border-ink/[0.08] text-[10px] text-ink/50">{g}</span>
            ))}
          </div>
        </div>
      ) : null}
      {narrative.produces?.length ? (
        <div>
          <div className="text-[10px] uppercase text-ink/35 mb-1">Produces</div>
          <div className="flex flex-wrap gap-1">
            {narrative.produces.map((p) => (
              <span key={p} className="px-2 py-0.5 border border-sky-500/20 bg-sky-500/[0.05] text-[10px] text-sky-400/80">{p}</span>
            ))}
          </div>
        </div>
      ) : null}
      {narrative.consumers?.length ? (
        <div>
          <div className="text-[10px] uppercase text-ink/35 mb-1">Consumers</div>
          <div className="flex flex-wrap gap-1">
            {narrative.consumers.map((c) => (
              <span key={c} className="px-2 py-0.5 border border-emerald-500/20 bg-emerald-500/[0.05] text-[10px] text-emerald-400/80">{c}</span>
            ))}
          </div>
        </div>
      ) : null}
    </div>
  );
}

function LineageJourney({ lineage }: { lineage: DataLineageView }) {
  const { journey, highlightIndex } = lineage;
  return (
    <div className="space-y-3 border border-ink/[0.08] p-4">
      <div className="flex items-center gap-2 text-[10px] uppercase tracking-wider text-ink/45">
        <Route size={12} /> Data lineage
      </div>
      <div>
        <div className="text-[12px] font-medium text-ink/70">{journey.title}</div>
        <div className="text-[10px] text-ink/40">{journey.subtitle}</div>
      </div>
      <div className="space-y-0">
        {journey.steps.map((step, i) => {
          const active = i === highlightIndex;
          return (
            <div key={step.id} className="flex flex-col items-center">
              <div
                className={cn(
                  'w-full text-center px-3 py-2 border text-[11px]',
                  active
                    ? 'border-amber-500/40 bg-amber-500/[0.08] text-amber-200/90 font-medium'
                    : 'border-ink/[0.08] text-ink/55',
                )}
              >
                <div>{step.label}</div>
                {step.table && <div className="text-[9px] font-mono text-ink/35 mt-0.5">{step.table}</div>}
                {step.description && <div className="text-[9px] text-ink/40 mt-1">{step.description}</div>}
                {active && <div className="text-[8px] uppercase tracking-wider text-amber-400/70 mt-1">You are here</div>}
              </div>
              {i < journey.steps.length - 1 && (
                <div className="flex flex-col items-center py-1 text-ink/25">
                  <div className="w-px h-2 bg-ink/15" />
                  <span className="text-[10px]">↓</span>
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}

function DetailPanel({ database, table }: { database: string; table: string }) {
  const [detail, setDetail] = useState<{
    table: string;
    registry: { owner: string; lifecycle: string; service?: string; canDelete: boolean; canArchive: boolean; canPartition: boolean; apis?: string[]; references?: string[]; referencedBy?: string[] };
    narrative?: TableNarrative;
    lineage?: DataLineageView | null;
    live?: { rows: number; idxScan: number; inserts: number; updates: number; sizePretty: string; deadRows: number; growthToday?: number | null; idxPct: number };
    statusLabel: string;
    sample?: { rows?: Record<string, unknown>[]; error?: string };
    error?: string;
  } | null>(null);
  const [loading, setLoading] = useState(true);
  const [panelView, setPanelView] = useState<'overview' | 'lineage'>('overview');

  useEffect(() => {
    setLoading(true);
    setPanelView('overview');
    fetch(`/api/data-catalog/tables/${database}/${table}`, { credentials: 'include' })
      .then((r) => r.json())
      .then(setDetail)
      .finally(() => setLoading(false));
  }, [database, table]);

  if (loading) return <div className="p-4 text-[11px] text-ink/40">Loading…</div>;
  if (!detail || detail.error) return <div className="p-4 text-[11px] text-rose-400/70">{detail?.error || 'Failed'}</div>;

  const live = detail.live;
  const reg = detail.registry;
  const narrative = detail.narrative;
  const lineage = detail.lineage;

  return (
    <div className="p-4 space-y-4 overflow-y-auto max-h-[70vh]">
      <div className="flex items-start justify-between gap-2">
        <div>
          <h3 className="text-sm font-mono font-semibold uppercase">{detail.table}</h3>
          {narrative && <p className="text-[11px] text-ink/50 mt-1">{narrative.purpose}</p>}
        </div>
        {lineage && (
          <button
            type="button"
            onClick={() => setPanelView(panelView === 'lineage' ? 'overview' : 'lineage')}
            className={cn(
              'shrink-0 flex items-center gap-1 px-2 py-1 border text-[10px]',
              panelView === 'lineage' ? 'border-amber-500/30 bg-amber-500/[0.08] text-amber-300/90' : 'border-ink/[0.1] text-ink/50 hover:text-ink/70',
            )}
          >
            <Route size={11} /> Data lineage
          </button>
        )}
      </div>

      {panelView === 'lineage' && lineage ? (
        <LineageJourney lineage={lineage} />
      ) : (
        <>
          {narrative && <NarrativeBlock narrative={narrative} />}
          <div className="grid grid-cols-2 gap-3 text-[10px]">
            <div className="border border-ink/[0.06] p-2"><span className="text-ink/35">Owner</span><div>{reg.owner}</div></div>
            <div className="border border-ink/[0.06] p-2"><span className="text-ink/35">Service</span><div>{reg.service || '—'}</div></div>
            <div className="border border-ink/[0.06] p-2"><span className="text-ink/35">Lifecycle</span><div>{reg.lifecycle}</div></div>
            <div className="border border-ink/[0.06] p-2"><span className="text-ink/35">Status</span><div>{detail.statusLabel}</div></div>
          </div>
          {live && (
            <div className="grid grid-cols-4 gap-2 text-[10px] font-mono">
              {[
                ['Rows', live.rows], ['Reads (idx)', live.idxScan], ['Writes', live.inserts], ['Updates', live.updates],
                ['Size', live.sizePretty], ['Dead', live.deadRows], ['Growth', live.growthToday ?? '—'], ['Idx%', `${live.idxPct}%`],
              ].map(([k, v]) => (
                <div key={String(k)} className="border border-ink/[0.06] p-2">
                  <div className="text-ink/35">{k}</div>
                  <div>{typeof v === 'number' ? v.toLocaleString() : v}</div>
                </div>
              ))}
            </div>
          )}
          <div className="text-[10px] space-y-1">
            <div><span className="text-ink/35">Can delete?</span> {reg.canDelete ? 'Yes (with review)' : 'No'}</div>
            <div><span className="text-ink/35">Can archive?</span> {reg.canArchive ? 'Yes' : 'No'}</div>
            <div><span className="text-ink/35">Can partition?</span> {reg.canPartition ? 'Eventually' : 'No'}</div>
            {reg.apis?.length ? <div><span className="text-ink/35">APIs:</span> {reg.apis.join(', ')}</div> : null}
          </div>
          {detail.sample?.rows?.length ? (
            <div>
              <div className="text-[10px] uppercase tracking-wider text-ink/40 mb-2">Sample rows</div>
              <pre className="text-[9px] font-mono overflow-x-auto border border-ink/[0.06] p-2 bg-ink/[0.02] max-h-48">
                {JSON.stringify(detail.sample.rows, null, 2)}
              </pre>
            </div>
          ) : null}
        </>
      )}
    </div>
  );
}

export const ArchitectureExplorer: React.FC = () => {
  const [data, setData] = useState<DataCatalogResponse | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [view, setView] = useState<'living' | 'tables' | 'pipeline' | 'events'>('living');
  const [category, setCategory] = useState<CatalogCategory | 'all'>('all');
  const [selected, setSelected] = useState<CatalogTableCard | null>(null);

  const load = useCallback(async () => {
    setBusy(true);
    setError(null);
    try {
      const res = await fetch('/api/data-catalog', { credentials: 'include' });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      setData(await res.json());
    } catch (e: unknown) {
      setError((e as Error).message);
    } finally {
      setBusy(false);
    }
  }, []);

  useEffect(() => { void load(); }, [load]);

  const cards =
    category === 'all'
      ? data?.tables || []
      : data?.categories[category] || [];

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between gap-3 flex-wrap">
        <div>
          <h2 className="text-sm font-semibold text-ink/70 flex items-center gap-2">
            <Layers size={14} /> Living Architecture
          </h2>
          <p className="text-[10px] text-ink/40 mt-0.5">Knowledge substrate — Harvest · Judicium · H3XA · Cascades</p>
        </div>
        <button type="button" onClick={() => void load()} disabled={busy} className="flex items-center gap-1.5 px-3 py-1.5 border border-ink/[0.08] text-[11px] text-ink/55">
          <RefreshCw size={12} className={busy ? 'animate-spin' : ''} /> Refresh
        </button>
      </div>

      {error && <div className="text-[11px] text-rose-400/80 border border-rose-500/20 p-3">{error}</div>}

      {data && (
        <>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
            {data.databases.map((db) => (
              <div key={db.id} className="border border-ink/[0.06] p-3">
                <div className="text-[10px] uppercase text-ink/40">{db.label}</div>
                <div className="text-lg font-mono text-ink/75">{db.connected ? db.totalRows.toLocaleString() : '—'}</div>
                <div className="text-[10px] text-ink/35">{db.tableCount} tables · {db.totalSizePretty}</div>
                {!db.connected && db.error && <div className="text-[9px] text-amber-400/70 mt-1">{db.error}</div>}
              </div>
            ))}
            <div className="border border-ink/[0.06] p-3">
              <div className="text-[10px] uppercase text-ink/40">Cascades</div>
              <div className="text-lg font-mono text-ink/75">{data.cascades?.connected ? 'OK' : '—'}</div>
              <div className="text-[10px] text-ink/35 truncate">{data.cascades?.url || 'not connected'}</div>
            </div>
          </div>

          <div className="flex gap-1 flex-wrap border-b border-ink/[0.06] pb-2">
            {(['living', 'tables', 'pipeline', 'events'] as const).map((v) => (
              <button key={v} type="button" onClick={() => setView(v)}
                className={cn('px-3 py-1 text-[10px] uppercase tracking-wider', view === v ? 'bg-ink/[0.08] text-ink/75' : 'text-ink/40')}>
                {v}
              </button>
            ))}
          </div>

          {view === 'living' && data.living && (
            <div className="grid md:grid-cols-2 gap-4">
              {[
                { title: 'Growing', items: data.living.growing, icon: Activity },
                { title: 'Needs attention', items: data.living.needsAttention, icon: AlertTriangle },
                { title: 'Schema bleed', items: data.living.sharedSchema.slice(0, 8), icon: Box },
                { title: 'Duplicated across DBs', items: data.living.duplicated.map((d) => ({ table: d.table, database: d.databases.join(', '), live: { rows: 0, heat: 'unused' as const } })), icon: Database },
              ].map(({ title, items, icon: Icon }) => (
                <div key={title} className="border border-ink/[0.06] p-3">
                  <div className="text-[10px] uppercase tracking-wider text-ink/45 flex items-center gap-1.5 mb-2"><Icon size={11} />{title}</div>
                  {items.length ? (
                    <ul className="space-y-1 text-[10px] font-mono">
                      {(items as any[]).slice(0, 8).map((item, i) => (
                        <li key={i} className="text-ink/55">
                          {'table' in item ? `${item.table}${item.live?.growthToday != null ? ` (+${item.live.growthToday})` : ''}` : `${item.table} → ${item.database}`}
                        </li>
                      ))}
                    </ul>
                  ) : <div className="text-[10px] text-ink/30">None</div>}
                </div>
              ))}
            </div>
          )}

          {view === 'tables' && (
            <div className="flex gap-4 min-h-[420px]">
              <div className="w-full md:w-1/2 space-y-2">
                <div className="flex flex-wrap gap-1">
                  <button type="button" onClick={() => setCategory('all')} className={cn('px-2 py-0.5 text-[9px]', category === 'all' ? 'bg-ink/[0.1]' : 'text-ink/40')}>All</button>
                  {(Object.keys(CATEGORY_LABELS) as CatalogCategory[]).map((c) => (
                    <button key={c} type="button" onClick={() => setCategory(c)} className={cn('px-2 py-0.5 text-[9px]', category === c ? 'bg-ink/[0.1]' : 'text-ink/40')}>
                      {CATEGORY_LABELS[c]} ({data.categories[c]?.length || 0})
                    </button>
                  ))}
                </div>
                <div className="space-y-2 max-h-[60vh] overflow-y-auto pr-1">
                  {cards.map((card) => (
                    <TableCard key={`${card.database}-${card.table}`} card={card} onSelect={setSelected} selected={selected?.table === card.table && selected?.database === card.database} />
                  ))}
                </div>
              </div>
              <div className="hidden md:block w-1/2 border border-ink/[0.06] bg-ink/[0.02]">
                {selected ? <DetailPanel database={selected.database} table={selected.table} /> : (
                  <div className="p-8 text-center text-[11px] text-ink/35">Select a table card</div>
                )}
              </div>
            </div>
          )}

          {view === 'pipeline' && (
            <div className="border border-ink/[0.06] p-4 overflow-x-auto">
              <div className="flex flex-col items-center gap-1 min-w-[320px]">
                {data.pipeline.nodes.map((node, i) => (
                  <React.Fragment key={node.id}>
                    <div className="border border-ink/[0.12] px-4 py-2 text-center min-w-[200px]">
                      <div className="text-[11px] font-semibold">{node.label}</div>
                      <div className="text-[9px] text-ink/40">{node.owner} · {node.tables.join(', ')}</div>
                      <div className="text-[9px] text-ink/45 mt-1">{node.description}</div>
                    </div>
                    {i < data.pipeline.nodes.length - 1 && (
                      <div className="text-ink/30 flex flex-col items-center">
                        <div className="w-px h-3 bg-ink/20" />
                        <GitBranch size={10} className="rotate-90" />
                        <div className="text-[8px] text-ink/35">{data.pipeline.edges.find((e) => e.from === node.id)?.label}</div>
                      </div>
                    )}
                  </React.Fragment>
                ))}
              </div>
            </div>
          )}

          {view === 'events' && (
            <div className="space-y-2 max-h-[50vh] overflow-y-auto">
              {(data.events || []).map((ev: any) => (
                <div key={ev.id} className="border border-ink/[0.06] px-3 py-2 text-[10px]">
                  <span className="text-ink/35 font-mono">{new Date(ev.created_at).toLocaleString()}</span>
                  <span className="mx-2 text-ink/50">{ev.event_type}</span>
                  {ev.aggregate_type && <span className="text-ink/40">{ev.aggregate_type}:{ev.aggregate_id}</span>}
                </div>
              ))}
              {!data.events?.length && <div className="text-[11px] text-ink/35">No domain_events yet</div>}
            </div>
          )}
        </>
      )}
    </div>
  );
};
